name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build DOcker image
        run: |
          docker build -t hello-world-app .

      - name: tag docker image
        run: |
          docker tag hello-world-app balav8/hello-world-app:latest

      - name: Push docker image
        run: |
          docker push balav8/hello-world-app:latest
